### ISSUE TITLE
[Bug 1.18] Ray form Null pointer

### ISSUE THREAD

**Issue by JaceEthaniel** [DerringersMods/TooManyGlyphs#1]
Attempting to use the Ray form on a server results in a Null Pointer exception "this.BASE_RANGE is null"

**Comment by DerringersMods** [comment]
Does [this build](https://www.curseforge.com/minecraft/mc-mods/too-many-glyphs/files/3721969) resolve the issue?

**Comment by JaceEthaniel** [comment]
Sorry for the late reply. Yes, that build resolves the issue.

**Comment by DerringersMods** [comment]
I guess I have an issue to file against AN, because that produces ugly results.

**Comment by JaceEthaniel** [comment]
It looks like the config file has BASE_RANGE defaulted with a range from 0.0 to the max value of the double, which may have caused the issue. 0 * 0 = 0, which would throw the null pointer exception. Is there a way to tell AN how to set up the config files? Maybe by having your add-on alter the config file to ensure certain variables are not too low when it loads? Could set up a check to make sure the range is not 0.0 ~ max and if it is have it alter the config and return a predefined range.
I'm not all too familiar with Java programming or I'd probably give a better suggestion, sorry.
